### ISSUE TITLE
Deprecated API Note

### ISSUE THREAD

**Issue by codenoobforreal** [emostar/flutter-libphonenumber#39]
<img width="919" alt="C664845E-EC3A-41C6-8EDC-5232BB357B8F" src="https://user-images.githubusercontent.com/18373253/133620883-71879c7e-822b-4e2a-8a07-ab4f9f4010aa.png">
<img width="839" alt="9B8C102D-5C4B-432B-AFC8-69359EC13FD2" src="https://user-images.githubusercontent.com/18373253/133620911-29e474d0-b7e7-4c6e-813d-544a3a08589d.png">

close it if it is not related

**Comment by sebastianbuechler** [comment]
`The plugin `libphonenumber` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.`

**Comment by Smithtekk** [comment]
Getting same issue on Flutter 2.6.0-12.0.pre89. Any update on a fix here @emostar

**Comment by emostar** [comment]
This should be fixed with v2.0.2 of the library.
